services:
  database-dev:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - PGHOST=${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
